mrc-ide/individual

DESCRIPTION, docker/Dockerfile, docker/Dockerfile.dev, inst/include/ProcessAPI.h
* This allows inheritance and mocking
* This requires a virtual destructor and therefore copy/move
constructor/assignments too
=> Make methods of the api virtual:

.gitignore, R/RcppExports.R, R/api.R, inst/include/ProcessAPI.h, inst/include/State.h, man/SimAPI.Rd, src/RcppExports.cpp, src/process_api.cpp
Hello MRC IDE team! I am creating a small pull request to add functionality addressing issue #38 
It exposes a new method `SimAPI$get_state_size` taking the same arguments as `SimAPI$get_state`, and the internal functions follow as closely as possible the logic from `process_get_state`.
=> implement querying number of individuals in a state

R/double_variable.R, tests/testthat/test-updates.R
This does nothing
```r
my_variable$queue_update(3, numeric(0))
```
but this fills my_variable with 3
```r
my_variable$queue_update(3, Bitset$new(my_variable$size))
```
This commit adds a fix for that.
=> Ignore empty bitset updates

inst/include/Event.h, tests/testthat/test-events.R, tests/testthat/test-prefab.R
Event listeners can be triggered with a timestep of 0. This fixes it
=> Make event time start at 1

R/RcppExports.R, R/categorical_variable.R, R/double_variable.R, R/integer_variable.R, inst/include/CategoricalVariable.h, inst/include/DoubleVariable.h, inst/include/IntegerVariable.h, man/CategoricalVariable.Rd, man/DoubleVariable.Rd, man/IntegerVariable.Rd, src/RcppExports.cpp, src/categorical_variable.cpp, src/double_variable.cpp, src/integer_variable.cpp, tests/testthat/test-variables.R
This PR adds `get_size_of` methods to IntegerVariable, CategoricalVariable, and DoubleVariable to query the number of individuals in a state without returning a bitset. For IntergerVariable  the user may either ask for the number of values in some set of value or in a interval [a,b]. For DoubleVariable the user asks for the number of values within some interval [a,b]. CategoricalVariable takes a vector of strings as the set to be matched against.
This also adds `get_index_of` to DoubleVariable to return a bitset of individuals whose value is within the interval [a,b].
Please let me know if I am submitting this PR into the wrong upstream branch! I think dev is the right one for it to go but I'm not certain.
=> query number of individuals in set for all variable types

R/RcppExports.R, R/bitset.R, inst/include/IterableBitset.h, man/Bitset.Rd, src/RcppExports.cpp, src/bitset.cpp, tests/testthat/test-bitset.R
Being able to do XOR on two bitsets is useful when dealing with complicated divisions of state space, this PR adds (and tests) that functionality.
=> Add xor for two bitsets

vignettes/Performance.Rmd
This PR should close out #75 , adds explanation of how to get RcppExports.cpp to see types in "individual.h" and links to the appropriate place in the Rcpp docs for more info.
=> add step to get RcppExports.cpp to see types in Performance vignette

vignettes/Performance.Rmd
Adds a section to demonstrate the bitset$sample() and bitset$set_difference() pattern being faster than calling filter_bitset() twice. It's a pretty common pattern so worth showing people up front. Also add the step of creating src/Makevars specifying the c++14 standard to the guide on how to make a package that links with "individual"; without that it won't compile.
=> Updates to Performance vignette

inst/include/Event.h
Make virtual destructors for events. 🤦 C++ inheritance 101
R gets an `XPtr<EventBase>` so the R garbage collector could only delete that. To delete the derived Event or TargetedEvent the destructor needs to be virtual.
You could quickly recreate the leak with: `R -e "devtools::test(filter='event')" -d 'valgrind --leak-check=full'`
=> Fix Event memory leak:

R/RcppExports.R, R/integer_variable.R, src/RcppExports.cpp, src/integer_variable.cpp
Somehow when I addressed this issue for the `get_size_of` method for IntegerVariable objects https://github.com/mrc-ide/individual/pull/98#issuecomment-848964943 I forgot to make that switch for the `get_index_of` method. This adds the check to the R6 class method that dispatches the correct C++ method for returning individuals whose value is in a vector of values or is equal to a scalar value.
=> add checks for scalar vs. vector in integer variable get_index_of method

vignettes/Performance.Rmd
small but important misspelling; now the link to `IntegerVariable` help page works!
=> individual::IntegerVector misspelling in performance vignette

R/bitset.R, tests/testthat/test-bitset.R
This is a very small PR to check if `filter_bitset` will get either a vector of length 0 or an empty bitset for argument `other` and straightaway return an empty bitset if so rather than calling the c++ sampling code. It's a bit faster on a bitset of size 1e5.
=> check if filter_bitset will return empty bitset

.Rbuildignore, R/bitset.R, R/categorical_variable.R, R/double_variable.R, R/event.R, R/integer_variable.R, R/render.R, R/targeted_event.R, inst/include/Variable.h, src/event.cpp, src/prefab.cpp
This PR addresses:
1. [compiler warnings in LTO check](https://www.stats.ox.ac.uk/pub/bdr/LTO/individual.out) by adding virtual dtor to base class `Variable`
2. [NOTE regarding namespace in imports field](https://www.r-project.org/nosvn/R.check/r-release-macos-arm64/individual-00check.html) by removing `R6::` qualifier from calls to `R6Class`; may be related to this [issue](https://stat.ethz.ch/pipermail/r-package-devel/2017q4/002066.html).
3. add `.vscode` to the .Rbuildignore file
Tests were ran on rhub with the following platforms `c("macos-highsierra-release-cran","windows-x86_64-release","solaris-x86-patched","debian-gcc-release","ubuntu-gcc-release")` and passed with 0 relevant NOTEs.
=> get rid of CRAN check NOTEs

inst/include/DoubleVariable.h, inst/include/IntegerVariable.h, tests/testthat/test-variables.R
This PR should fix #119, and adds a test to check for this in the future. The checks are at the c++ level because the length of the stored vectors is not available at the R level; I think that makes sense and this is a fine place to do the check, this is simply a weird edge case.
=> check for bitset sizes when getting values for integer/double variables

R/bitset.R, man/Bitset.Rd, tests/testthat/test-bitset.R
if `Bitset$choose` is given `k` equal to size of the bitset, do nothing; this used to throw an error which means users have to check for size of `k` versus the bitset prior to using it, which disrupts the way it is used in modelling.
=> bitset choose now allows k = n

R/integer_variable.R, tests/testthat/test-variables.R
Sometimes it is useful to call `IntegerVariable$get_size_of(a = val1, b = val2)` in a modeling context where it is possible for `val1 = val2`; right now this is considered an error and the code requires `a < b`. I propose that in this case (`a = b`) the method should revert to the set behavior with a set consisting of a single element `integer_variable_get_index_of_set_scalar`. This PR implements that for both `get_size_of` and `get_index_of` methods and adds another test.
=> IntegerVariable get methods now allow a=b which defaults to set behavior

R/bitset.R
@giovannic I think I found the what's giving the UBSCAN error on CRAN's tests. Using the docker image from [Rich's blog post](https://reside-ic.github.io/blog/debugging-and-fixing-crans-additional-checks-errors/) I found the error occurring at test-bitset.R:186:3, when calling `b$choose(-1)`. See log below:
```
Start test: bitset choose behaves properly when given an empty bitset
test-bitset.R:186:3 [success]
/usr/local/RDcsan/lib/R/site-library/Rcpp/include/Rcpp/internal/caster.h:30:25: runtime error: -1 is outside the range of representable values of type 'unsigned long'
```
I guess that -1 gets cast to a `size_t` below which causes the issue. This fix should prevent that (it doesn't raise any UBSCAN warnings after I implemented it locally). …
=> bitset$choose should never be passed negative number

README.md, vignettes/Contributing.Rmd
@giovannic I added a statement of need section to the README as requested in #133 to conform to the [JOSS requirements for documentation here](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation). The text is adapted from the paper to read better to a first time user scrolling over the readme in the repo or on CRAN.
=> add statement of need to README.md

R/categorical_variable.R, src/categorical_variable.cpp, tests/testthat/test-categoricalvariable.R
Currently the following code does not cause an error, in contrast to how IntegerVariable and DoubleVariable handle bad bitset input when queuing updates:  
```
c <- CategoricalVariable$new(categories = c("A","B"),initial_values = rep(c("A","B"),each=10))
c$queue_update(value = "A",index = Bitset$new(50)$insert(c(15, 25, 50)))
```
It's nicer to make the error handling consistent, as then the error can be traced more easily back to the process that queued the bad indices, rather than starting from when it tried to apply the update. This PR also adds some tests to catch these cases.
=> check for bad bitset index when queuing CategoricalVariable updates 

inst/include/IntegerVariable.h, src/integer_variable.cpp
This very small PR just takes the `IntegerVariable::get_size_of_set_vector` and `IntegerVariable::get_size_of_set_scalar` methods and makes them a single overloaded method, for consistency with how the other methods that may take either a vector or a scalar are implemented.
=> consistent C++ API for IntegerVariable

R/event.R
Fix a simple bug that prevents event listeners written in C++ from executing properly.
=> fix bug with cpp event listeners

.github/workflows/pkgdown.yml, R/RcppExports.R, R/render.R, README.md, inst/include/RenderVector.h, inst/include/individual_types.h, src/RcppExports.cpp, src/render_vector.cpp, tests/performance/bench-render.R, tests/performance/utils.R, tests/testthat/test-render.R
The `Render$render` method is used throughout a simulation to store data that needs outputting at the end. It does so by creating a vector per metric, large enough to fit all timesteps.
Unfortunately, each time the `render` method is called, the assignment into the vector actually creates a new copy, instead of modifying it in-place. For long simulations (ie. tens of thousands of timesteps), these vectors are both fairly large and get copied over and over again at each timestep, to the point where the `render` method dominates the execution time.
The core of the problem can easily be reproduced by recreating the same conditions of the `Render` class, using a vector stored inside of an environment:
```r
e <- new.env(parent=emptyenv())
e$vector = rep(0, 10)
tracemem(e$vector)
e$vector[[0]] …
```
=> Speedup render by avoiding repeated vector copies.

R/simulation.R, man/Event.Rd, man/TargetedEvent.Rd, man/restore_state.Rd, man/simulation_loop.Rd, tests/testthat/test-checkpoint.R, vignettes/Checkpoint.Rmd
It can have suprising side effects by resetting the user global RNG state to a fixed value, and also get in the way of doing stochastic simulations where we actually want to sample many different futures from a given start point.
The only time where a user actually wants to restore the random number generator state is probably when writing tests that compare a continuous run against a resumed one. They can opt-in to that behaviour with a new argument to `simulation_loop` called `restore_random_state`.
=> Don't restore the random number generator state by default.

.github/workflows/pkgdown.yml, NEWS.md, _pkgdown.yml
I hadn't added the new types and functions to the pkgdown index, which broke the site rebuild. This didn't get caught by CI because pkgdown was only running on the master branch.
Added the missing index entries and changed the CI to run pkgdown everywhere. It only does the actual push when on the master branch.
=> Fix broken pkgdown index.

inst/include/Event.h, tests/testthat/test-events.R, tests/testthat/test-targetedevent.R
The `Event::should_trigger` method uses `.begin()` on the set of times at which it needs to fire to compare that value with the current tick. However it was missing a check in the case of an empty set. When that happens, `begin()` returns a pointer to uninitialized memory and we we reading garbage out of it. If that garbage happens to be equal to the current time step, the event would fire spuriously, even though it wasn't meant to.
The fix is straightforward: we just need to check if the set is empty before reading from the set. If it is empty then the event never triggers.
=> Check if the schedule is empty before reading it.

R/RcppExports.R, R/event.R, inst/include/Event.h, src/RcppExports.cpp, src/event.cpp, tests/testthat/test-events.R, vignettes/Checkpoint.Rmd
By default, when restoring the simulation state all previous schedules on events are cleared and restored from the saved state. This goes against use cases that wish to resume a simulation with different intervention schedules to compare effects. In those use cases, a different initialization sequence is used when creating the simulation, and we do not want that to be cleared and overwritten.
The new `restore` flag, when set to false, overrides this default behaviour and the state of an Event is (mostly) unaffected by a restore. Thanks to this, a new event schedule, that is unrelated to the schedule of the original run, can be configured.
----
~~Unlike other event types, which have a `schedule` method, the `StaticEvent` follows a fixed list of times at which it triggers, defined at …
=> Add a restore flag to the Event constructor.

man/Event.Rd
I changed a function signature in mrc-ide/individual#180, but had not regenerated the `.Rd` files.
=> Re-generate documentation files.

inst/include/NumericVariable.h, src/RcppExports.cpp, src/bitset.cpp, src/double_variable.cpp, src/integer_variable.cpp
Couple of hotspots found while running malariasimulation with larger population size. This PR gives a 10% speedup when using population size of 1M.
The most suprising change comes from a modification to the signature of Rcpp-exported functions. Some of them used to accept a `const std::vector` as an argument. However when doing so Rcpp creates an extra unexpected copy in the wrapping code. We end up with two copies, once from R memory to an std::vector in the generated code, and a second one when the method is called. If argument is non-const, Rcpp does not create the intermediate object and the copy is avoided.
This behaviour comes from the difference between the `InputParameter` and `ConstInputParameter` classes in Rcpp's [InputParameter.h] file.
Other changes include:
- Return a …
=> Optimize some memory copies away.

inst/include/IterableBitset.h, tests/testthat/test-bitset.R
The existing bitset sampling implementation works by using a binomial distribution to decide how many bits to keep, randomly chooses the indices of those bits, sorts the vector of indices and finally iterates over all the bits one by one to clear those not contained in the vector.
This can be very inefficient, in particular when sampling over large bit sets with a very low sampling rate. In that case, the list of indices to keep is roughly as large as the bitset itself, and sorting it requires O(nlog(n)) time, which ends up being significant.
Additionally, walking over every single bit, set or not, to be cleared or not, is pretty inefficient as well.
This commit optimizes the implementation through a few methods:
- Instead of sampling and sorting indices to keep, it randomly samples the …
=> Optimize the bitset sampling algorithm.

inst/include/vector_variables.h
When a queued update replaces an entire variable, we can re-use the vector contained in the update by moving it over, instead of copying it.
This situation is actually pretty common in malariasimulation, where exponentially decaying variables are entirely overwritten at each time step. This change speeds up the simulation by about 5% for a 1M population.
=> Avoid a copy on full vector replacement by using std::move.

R/simulation.R, tests/testthat/test-prefab.R, tests/testthat/test-simulation-e2e.R
Because of how R assigns names to stack frames, all processes in a typical individual simulation would end up being called `p`. This makes it difficult to interpret profiling results.
R uses the name of the variable the called function is bound to. By dynamically creating a variable with a chosen name and using `eval` to execute that variable, we can get the stack frame to show up with any desired name.
This uses this trick to allow the list of processes to be given names, and these names are used in the calls.
Below is a comparison of the before and after of looking at a malariasimulation profile. Instead of everything being grouped under a single `p` node, there are now distinct nodes for each process.
=> Allow processes to be named.

DESCRIPTION, R/RcppExports.R, R/bitset.R, man/filter_bitset.Rd, man/restore_object_state.Rd, src/RcppExports.cpp, src/bitset.cpp, tests/performance/bench-bitset.R, tests/testthat/test-bitset.R, vignettes/Performance.Rmd
In addition to a vector of numerical indices and another bitset, the filter_bitset now accepts a vector of logicals (ie. booleans). Each set bit of the bitset is included in the return value only if the corresponding value in the logical vector is TRUE.
Given `v` a logical vector, `filter_bitset(b, v)` is equivalent to the already supported `filter_bitset(v, which(v))` but is more performant. The new semantics also align with subsetting of R vectors, which similarly supports either a vector of indices or vector of logicals.
=> Support vectors of logicals as an argument to filter_bitset.

inst/include/IterableBitset.h
The variable stores the number of bits per word and is used throughout the implementation to split a position into a word index and bit position in the word.
The value can be determined statically from the size of the template parameter and does not need to be stored as a field. Keeping it as a `constexpr` value allows the compiler to optimize operations that use it. In particular, since the value is always a power of two, any multiplication, division, and modulo operations by this value, which are quite common, can be turned into bit shifts or masks by a constant.
The performance impact of this change is quite small, but measurable, at around 2% for a 1M malariasimulation run, with no downside.
=> Make num_bits a constant expression.

R/RcppExports.R, R/bitset.R, man/Bitset.Rd, src/RcppExports.cpp, src/bitset.cpp, tests/testthat/test-bitset.R
This copies the value from one bitset to another one.
=> Add a method to overwrite a bitset.
